# Generated by Django 4.1.5 on 2023-08-28 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
    ]
