# Generated by Django 4.1.5 on 2023-09-09 12:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='data',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
