# Generated by Django 4.1.5 on 2023-08-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='reviewer',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='rating',
        ),
        migrations.AddField(
            model_name='blog',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='blog_banner/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_pic',
            field=models.ImageField(blank=True, null=True, upload_to='blog_pic/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='categories',
            field=models.JSONField(default=list, null=True),
        ),
    ]
