# Generated by Django 4.1.5 on 2023-08-28 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_follower'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='categories',
        ),
        migrations.CreateModel(
            name='Category_associate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='blogs.blog')),
                ('category_name', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='blogs.categories')),
            ],
        ),
    ]
