# Generated by Django 4.1.5 on 2023-09-09 10:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_categories_remove_blog_categories_category_associate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='banner',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
