# Generated by Django 4.1.5 on 2023-09-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_banner_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_banner/'),
        ),
    ]
