# Generated by Django 4.1.5 on 2023-09-09 23:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default='https://wallpapers.com/images/hd/gaming-profile-pictures-pbhlm4b7w9u0lwle.jpg', max_length=255, verbose_name='image'),
        ),
    ]
